### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by XelnoX** [BME-MIT-IET/altF4-iet-2020#3]
For the first steps, @kovilevi98 and @XelnoX will make some tests, and the documentation will be done by @VitusRegina and @villamroland.

**Comment by villamroland** [comment]
Added [commit1](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/4020d550518eb6870ca2574719ebd45e503509e5l), [commit2](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/a5580924a813902a99d2c8738a1666ede1aa521c)

**Comment by VitusRegina** [comment]
Added [iet-hf finished](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/c35c5d0326e7f3d88c40df70cab56080f67d42a7)

**Comment by XelnoX** [comment]
I think everything is perfect! Well done!
