### ISSUE TITLE
Set up sonarcloud for testing

### ISSUE THREAD

**Issue by kovilevi98** [BME-MIT-IET/altF4-iet-2020#4]
@XelnoX  and @kovilevi98 set up the sonarcloud online and update the build.gradle and add a new Action .

**Comment by XelnoX** [comment]
Sonarcloud set up completed [sonarSetup](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/82aebfbbe2955e33c32a4f8fb9becb8fc3206078)

**Comment by villamroland** [comment]
Sonarcloud working test completed, closing issue.
