### ISSUE TITLE
Manual code review

### ISSUE THREAD

**Issue by XelnoX** [BME-MIT-IET/altF4-iet-2020#5]
We made our own checklist, using this site: [source](https://nyu-cds.github.io/effective-code-reviews/03-checklist/). There are four main spects: general, security, testing and documentation.
The checklist is the following:
1) Documentation{
	Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’?
	Do comments exist and describe the intent of the code? If so, do the comments understandable?
	Is any unusual behavior or edge-case handling described?
}

2) Security{
	Are all data inputs checked (for the correct type, length, format, and range) and encoded?
	Are output values checked and encoded? Is it checked in a proper way?
	Are invalid parameter values handled, and are returning errors being caught? If so, how?
}

3) Testing{
	Is the code testable? If so, what kind of tests should be written?
	Do tests exist, and are they comprehensive? Are they understandable (name, comments, etc.)?
	Do unit tests actually test that the code is performing the intended functionality?
}

4) General{
	Does the code work? Does it perform its intended function, the logic is correct etc. If so, what is it's function?
	Is there any redundant or duplicate code? If so, can it be done in an easier way?
	Do loops have a set length and correct termination conditions? (Is there any infinite cycle?)
}

All of us should choose one main aspect, and do the code review by the given points.

**Comment by kovilevi98** [comment]
I will do the Documentation

**Comment by villamroland** [comment]
I'm going to do the security check.

**Comment by kovilevi98** [comment]
I've done the documentation manual review [commit](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/35f9b83ef74d728d05b79556ca97f93473915003)

**Comment by VitusRegina** [comment]
I will do the General

**Comment by VitusRegina** [comment]
I've done the general manual review [general](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/136a2a0662e519be072e5e14aad6c1028f2dbb8a)

**Comment by villamroland** [comment]
I've done the security check. [commit](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/7964f9f30989aecfea09e780888f84ff064351dd)

**Comment by XelnoX** [comment]
Ok, then I will do the testing review tonight, with that, and with the check of the result of SonarQube we will finish the first part of the homework.

**Comment by XelnoX** [comment]
I finished my part of the manual code review [(tests review)](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/fe90b87305fb3d64c430db7c68d614c73c3ebcf7), and I checked your's as well. So someone please read my documentation and if everything is ok, then close this issue.

**Comment by villamroland** [comment]
Everything is okay, closing the issue.
