### ISSUE TITLE
SonarQube tests and fixes

### ISSUE THREAD

**Issue by villamroland** [BME-MIT-IET/altF4-iet-2020#6]
The team will jointly review the warnings listed by SonarQube and, after a discussion, fix what they consider critical, important, and worthy(possible to improve as fast as it is worth it).

**Comment by kovilevi98** [comment]
We have solved all of the problem what were important we thought. There are the commits [delete unnecesary code](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/78fa88bae4c644afb9d3a565743c410ce4a6da4f) , [unneccessary else if branch deleted from code](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/710e94976747d6ba19dd29136b2a59a6a239baf6) , [Throwable changed to Exception](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/6644efd29a5bce662d9b1958041ab8f855117820) , [checked suggestion, but left it as it was](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/8be8b42aba717f17538e7397a94edeccdd0c66b5) , [we made the change as it was suggested](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/67d34965ce5bfb34d8aa33fbab052cc5a6b74f70) , [newInstance is deprecated so we added getDeclaredConstructor() call](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/1c32de1550554b24b06634c9b0ef862d38754219) , [try-catchdespite of throw](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/9a6b1acef58694053a9e9af24e0d3e6843e701c1) , [change string format](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/0e36d40ae16cd07cfcbeca080fed4010030d5251)

**Comment by villamroland** [comment]
We left 6 + 2 warnings unresolved.
> Cognitive Complexity is a measure of how hard the control flow of a method is to understand. Methods with high Cognitive Complexity will be difficult to maintain. 

It would be too time-consuming and complicated if we wanted to solve it all. With this, the essential part of the code, its logic, should be completely rethought from the beginning.

> Restricting the number of _break_ and _continue_ statements in a loop is done in the interest of good structured programming.
One _break_ and _continue_ statement is acceptable in a loop, since it facilitates optimal coding. If there is more than one, the code should be refactored to increase readability.

As before, a whole new logic should be created in the code.
