### ISSUE TITLE
Non functional testing

### ISSUE THREAD

**Issue by villamroland** [BME-MIT-IET/altF4-iet-2020#7]
@kovilevi98  and me(@villamroland ) are going to do that. We are testing what happens if we give a huge input and try to measure it.

**Comment by villamroland** [comment]
Documentation done. [commit](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/67e5d13ebf89cd70e741750cab1411c7f482e40b)

**Comment by XelnoX** [comment]
I saw the documentation and the tests everything is fine, so I close this issue!
