### ISSUE TITLE
setup Codacy

### ISSUE THREAD

**Issue by kovilevi98** [BME-MIT-IET/altF4-iet-2020#8]
I'm (@kovilevi98) going to set up Codacy and watch the differences between  sonarqube.

**Comment by kovilevi98** [comment]
I have already done the setup and the documentation as well [commit](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/4f753c487830431f540097a66fcca7aaf06ad7b2)

**Comment by villamroland** [comment]
Everything is okay, closing issue
