### ISSUE TITLE
Set up Cucumber and tests

### ISSUE THREAD

**Issue by kovilevi98** [BME-MIT-IET/altF4-iet-2020#9]
@XelnoX @villamroland  @kovilevi98 are going to do that

**Comment by kovilevi98** [comment]
Set up the gradle with the cucumber [comment](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/2b77576f79fa7629c34aaaae3b19afb17af0593f)

**Comment by kovilevi98** [comment]
The read and the write tests with Cucumber work [commit](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/b41d29c4d851fef81c253db37b5dfc468e532bfd)

**Comment by kovilevi98** [comment]
There is the documentation [commit](https://github.com/BME-MIT-IET/altF4-iet-2020/commit/12588726765b386e1611264ef628567ac061b2d7)

**Comment by VitusRegina** [comment]
Everything is alright
